services:
  dev-fe-bnb:
    container_name: dev-fe-bnb
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_WALLETCONNECT_PROJECT_ID=${VITE_WALLETCONNECT_PROJECT_ID}
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_MAPBOX_TOKEN=${VITE_MAPBOX_TOKEN}
    ports:
      - "3003:80"
    env_file:
      - .env
